version: "3.8"
services:

  npm: #nginx proxy manager
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - bridge
    restart: always
    volumes: 
      - /srv/npm/letsencrypt:/etc/letsencrypt
      - /srv/npm/data:/data
    #  condition: on-failure
