version: "3.8"

services:

  db: #mariadb
    container_name: database
    image: mariadb:latest
    ports:
      - 9910:3306
    environment:
      - MARIADB_ROOT_PASSWORD=123qwe
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - net_db:
      - net_app2: 
          ipv4_address: 172.20.0.2
    restart: always

  app_1: #phpmyadmin
    container_name: app_pma
    image: phpmyadmin:latest
    ports: 
      - 9911:80
    depends_on:
      - db
    environment:
      - PMA_HOST=database
    networks:
      - net_db
    restart: always

  app_2: #nextcloud
    container_name: app_nextcloud
    image: nextcloud:latest
    ports:
      - 9912:80
    depends_on:
      - db
     #environment:
      #- MARIADB_ROOT_PASSWORD=123qwe
      #- MARIADB_DATABASE=nextcloud
    restart: always
    volumes:
      - data-apps2:/var/www/html
      - /data/srv/apps/nextcloud:/var/www/html/data
    networks:
      net_app2:
        ipv4_address: 172.20.0.3 
      
networks:
  net_db:
    name: net_db
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
    
  net_app2:
    name: net_app2
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  data-db:
  data-apps2: